# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1174219677);
user_pref("app.update.lastUpdateTime.background-update-timer", 1174219676);
user_pref("browser.formfill.enable", false);
user_pref("browser.link.open_external", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 2);
user_pref("browser.preferences.privacy.selectedTabIndex", 0);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.0.11");
user_pref("browser.tabs.warnOnClose", false);
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.lastAppVersion", "1.5.0.11");
user_pref("extensions.update.enabled", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.http", "localhost");
user_pref("network.proxy.http_port", 9999);
user_pref("network.proxy.no_proxies_on", "");
user_pref("network.proxy.ssl", "localhost");
user_pref("network.proxy.ssl_port", 9999);
user_pref("network.proxy.type", 1);
user_pref("pref.browser.homepage.disable_button.blank_page", false);
user_pref("pref.privacy.disable_button.clear_history", false);
user_pref("privacy.item.cookies", true);
user_pref("privacy.item.passwords", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("signon.rememberSignons", false);
user_pref("xpinstall.whitelist.required", false);
